# -*- coding: utf-8 -*-
"""Copia de Trabajando con datos 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13MZszgAdvbzw2YbX9-yeQ-oFpUhRjv2p

# Selección de datos para modelización

Su conjunto de datos contiene demasiadas variables como para que pueda entenderlas o incluso imprimirlas. ¿Cómo puede reducir esta abrumadora cantidad de datos a algo que pueda entender?

Empezaremos por seleccionar algunas variables utilizando nuestra intuición. Cursos posteriores le mostrarán técnicas estadísticas para priorizar automáticamente las variables.

Para elegir variables/columnas, necesitaremos ver una lista de todas las columnas del conjunto de datos. Eso se hace con la propiedad columns del DataFrame (la línea inferior del código de abajo).
"""

import pandas as pd

melbourne_file_path = '/content/drive/MyDrive/pandas-data/melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path) 
melbourne_data.columns

# Los datos de Melbourne tienen algunos valores perdidos (algunas casas para las que no se registraron algunas variables).
# Aprenderemos a manejar los valores perdidos en un tutorial posterior.  
# Tus datos de Iowa no tienen valores perdidos en las columnas que utilizas. 
# Así que tomaremos la opción más simple por ahora, y eliminaremos las casas de nuestros datos. 
# No te preocupes mucho por esto por ahora, aunque el código es:

# dropna elimina los valores perdidos (piense en na como "no disponible")
melbourne_data = melbourne_data.dropna(axis=0)

"""# Selección del objetivo de predicción
Puede extraer una variable con anotación por puntos. Esta única columna se almacena en una Serie, que a grandes rasgos es como un DataFrame con una única columna de datos.

Utilizaremos la notación de puntos para seleccionar la columna que queremos predecir, que se denomina objetivo de predicción. Por convención, el objetivo de predicción se llama y. Así que el código que necesitamos para guardar los precios de la vivienda en los datos de Melbourne es
"""

y = melbourne_data.Price

"""# Selección de características
Las columnas que se introducen en nuestro modelo (y que luego se utilizan para hacer predicciones) se denominan "características". En nuestro caso, serían las columnas utilizadas para determinar el precio de la vivienda. A veces, utilizará como características todas las columnas excepto el objetivo. Otras veces será mejor utilizar menos características.

Por ahora, construiremos un modelo con sólo unas pocas características. Más adelante verá cómo iterar y comparar modelos construidos con diferentes características.

Seleccionamos múltiples características proporcionando una lista de nombres de columnas entre paréntesis. Cada elemento de la lista debe ser una cadena (entre comillas).

He aquí un ejemplo:
"""

melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

"""Por convención, estos datos se denominan X."""

X = melbourne_data[melbourne_features]

"""Repasemos rápidamente los datos que utilizaremos para predecir los precios de la vivienda utilizando el método de descripción y el método de la cabeza, que muestra las primeras filas."""

## Imprime las primeras filas

X.head()

"""Comprobar visualmente los datos con estos comandos es una parte importante del trabajo de un científico de datos. A menudo encontrarás sorpresas en el conjunto de datos que merecen una inspección más detallada.

# Creación del modelo
Utilizarás la librería scikit-learn para crear tus modelos. Al codificar, esta biblioteca se escribe como sklearn, como verás en el código de ejemplo. Scikit-learn es fácilmente la biblioteca más popular para modelar los tipos de datos típicamente almacenados en DataFrames.

Los pasos para construir y utilizar un modelo son:

Definir: ¿Qué tipo de modelo será? ¿Un árbol de decisión? ¿Otro tipo de modelo? También se especifican otros parámetros del tipo de modelo.
Ajustar: Capturar patrones a partir de los datos proporcionados. Este es el corazón del modelado.
Predecir: Justo lo que parece
Evaluar: Determinar la precisión de las predicciones del modelo.
He aquí un ejemplo de definición de un modelo de árbol de decisión con scikit-learn y su ajuste con las características y la variable objetivo.
"""

from sklearn.tree import DecisionTreeRegressor

# Define model. Specify a number for random_state to ensure same results each run
melbourne_model = DecisionTreeRegressor(random_state=1)

# Fit model
melbourne_model.fit(X, y)

"""Muchos modelos de aprendizaje automático permiten cierta aleatoriedad en el entrenamiento del modelo. Especificar un número para random_state le asegura obtener los mismos resultados en cada ejecución. Esto se considera una buena práctica. Puede utilizar cualquier número y la calidad del modelo no dependerá significativamente del valor exacto que elija.

Ahora tenemos un modelo ajustado que podemos utilizar para hacer predicciones.

En la práctica, querremos hacer predicciones para las nuevas viviendas que salgan al mercado y no para las viviendas de las que ya tenemos precios. Pero haremos predicciones para las primeras filas de los datos de entrenamiento para ver cómo funciona la función predecir.
"""

print("Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(melbourne_model.predict(X.head()))

"""# Tu primer modelo"""

import pandas as pd

iowa_file_path = '/content/train.csv'

home_data = pd.read_csv(iowa_file_path)
print(home_data.columns)

"""## Especificar objetivo de predicción
Seleccione la variable objetivo, que corresponde al precio de venta. Guárdela en una nueva variable llamada y. Tendrá que imprimir una lista de las columnas para encontrar el nombre de la columna que necesita.
"""

# imprimir la lista de columnas del conjunto de datos para encontrar el nombre del objetivo de predicción

y = home_data.SalePrice

"""## Crear X

Ahora creará un DataFrame llamado X que contendrá las características predictivas.

Como sólo quiere algunas columnas de los datos originales, primero creará una lista con los nombres de las columnas que quiere en X.

Utilizará sólo las siguientes columnas en la lista (puede copiar y pegar toda la lista para ahorrar algo de escritura, aunque todavía tendrá que añadir comillas):

- LotArea
- YearBuilt
- 1stFlrSF
- 2ndFlrSF
- FullBath
- BedroomAbvGr
- TotRmsAbvGrd

Después de crear esa lista de características, utilízala para crear el DataFrame que utilizarás para ajustar el modelo.
"""

# Crear la lista de características
feature_names = ["LotArea", "YearBuilt", "1stFlrSF", "2ndFlrSF", "FullBath", "BedroomAbvGr", "TotRmsAbvGrd"]

# Seleccionar los datos correspondientes a las características en feature_names
X = home_data[feature_names]

"""# Revisar datos
Antes de construir un modelo, echa un vistazo rápido a X para verificar que parece sensato
"""

# Revisar datos
# imprimir descripción o estadísticas de X
print(X.describe(),"\n")
# imprimir las primeras lineas
print(X.head())

"""# Especificar y ajustar el modelo
Cree un DecisionTreeRegressor y guárdelo en iowa_model. Asegúrese de que ha realizado la importación correspondiente desde sklearn para ejecutar este comando.

A continuación, ajuste el modelo que acaba de crear utilizando los datos en **X** y **y** que guardó anteriormente.
"""

# Importar DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor

# Especificar el modelo. 
# Para la reproducibilidad del modelo, establecer un valor numérico para random_state al especificar el modelo.
iowa_model = DecisionTreeRegressor(random_state=1)

# Hacer Fit al modelo
iowa_model.fit(X, y)

"""# Hacer predicciones
Realiza predicciones con el comando predecir del modelo utilizando X como datos. Guarda los resultados en una variable llamada predictions.
"""

predictions = iowa_model.predict(X.head())
print(predictions)