# -*- coding: utf-8 -*-
"""Copia de Trabajando con datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z1j8YSIatrPiYxVOl3PfG-kozR32ppF7

# Uso de Pandas para familiarizarse con los datos

El primer paso en cualquier proyecto de aprendizaje automático es familiarizarse con los datos. Para ello utilizarás la librería Pandas. Pandas es la principal herramienta que utilizan los científicos de datos para explorar y manipular datos. La mayoría de la gente abrevia pandas en su código como pd. Hacemos esto con el comando
"""

import pandas as pd

"""La parte más importante de la librería Pandas es el DataFrame. Un DataFrame contiene el tipo de datos que usted podría considerar como una tabla. Es similar a una hoja en Excel, o una tabla en una base de datos SQL.

Pandas tiene potentes métodos para la mayoría de las cosas que querrás hacer con este tipo de datos.

Como ejemplo, veremos datos sobre los precios de la vivienda en Melbourne, Australia. En los ejercicios prácticos, se aplicarán los mismos procesos a un nuevo conjunto de datos, que tiene los precios de la vivienda en Iowa.

[Datos del ejemplo (Melbourne)](https://drive.google.com/file/d/1tmtn7w-PfHnb9F5y1_26aHHOvWoAqV8X/view?usp=share_link)

Descargamos, cargamos y exploramos los datos con los siguientes comandos:


"""

# guardar la ruta del archivo en una variable para facilitar el acceso
melbourne_file_path = '/content/melb_data.csv'
# leer los datos y almacenarlos en DataFrame titulado melbourne_datas
melbourne_data = pd.read_csv(melbourne_file_path) 
# imprimir un resumen de los datos en melbourne_datas
melbourne_data.describe()

"""# Interpretación de los datos Descripción
Los resultados muestran 8 números para cada columna del conjunto de datos original. El primer número, el recuento, muestra cuántas filas tienen valores que no faltan.

Los valores que faltan se deben a muchas razones. Por ejemplo, el tamaño del segundo dormitorio no se recogería al encuestar una casa de 1 dormitorio. Volveremos al tema de los datos que faltan.

El segundo valor es la media, que es el promedio. Debajo, std es la desviación típica, que mide la dispersión numérica de los valores.

Para interpretar los valores mínimo, 25%, 50%, 75% y máximo, imagine que ordena cada columna de menor a mayor valor. El primer valor (el más pequeño) es el mínimo. Si recorres un cuarto de la lista, encontrarás un número que es mayor que el 25% de los valores y menor que el 75% de los valores. Ese es el valor del 25% (pronunciado "percentil 25"). Los percentiles 50 y 75 se definen de forma análoga, y el máximo es el número más grande.

# Caso practico

## Cargar datos

[Datos de practica](https://drive.google.com/file/d/1pxueUHUf-YyErkseZA3pfn3Si2pfWOJg/view?usp=sharing)

Descargamos, cargamos y comenzamos:
"""

import pandas as pd

# Ruta del archivo a leer
iowa_file_path = '/content/train.csv'

# Complete la siguiente línea para leer el archivo en una variable home_data
home_data = pd.read_csv(iowa_file_path)

"""## Leer datos"""

# Imprimir estadísticas resumidas en la línea siguiente
home_data.describe()

# ¿Cuál es el tamaño medio de los lotes (redondeado al número entero más próximo)?
avg_lot_size = home_data["LotArea"].mean().round()
print(avg_lot_size)

# As of today, how old is the newest home (current year - the date in which it was built)
newest_home_age = 2023 - home_data["YearBuilt"].max()
print(newest_home_age)